services:
  - type: web
    name: laravel-app
    runtime: docker
    env: docker
    repo: https://github.com/EidalPRO/ORTOGRAPHIC-XXVII.git
    plan: free
    region: oregon
    branch: master
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:YlnyKa3U8QI/AobLw2EeynLSugtEyvs+YucGIZCxSSA=  
      - key: APP_URL
        value: https://laravel-app.onrender.com  # Actualiza con la URL real de Render
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 65.99.225.56
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: cbtised3_ortographic
      - key: DB_USERNAME
        value: cbtised3_ortographic
      - key: DB_PASSWORD
        value: CBTis150ortographic@
